@echo off
REM TR: KUBBE V4 Font Download Script - OFFLINE DESTEK
REM EN: KUBBE V4 Font Download Script - OFFLINE SUPPORT
REM TR: Bu script Google Fonts'tan font dosyalarını indirir
REM EN: This script downloads font files from Google Fonts
REM TR: İnternet bağlantısı olmadan font kullanımını sağlar
REM EN: Enables font usage without internet connection

echo TR: KUBBE V4 Font İndirme Başlatıldı
echo EN: KUBBE V4 Font Download Started

REM TR: assets/fonts klasörünü oluştur
REM EN: Create assets/fonts folder
if not exist "assets\fonts" mkdir "assets\fonts"
echo TR: assets/fonts klasörü oluşturuldu
echo EN: assets/fonts folder created

REM TR: Font dosyalarını indir
REM EN: Download font files
echo TR: Font dosyaları indiriliyor...
echo EN: Downloading font files...

REM TR: Outfit fontları
REM EN: Outfit fonts
echo TR: Outfit-Regular indiriliyor...
echo EN: Downloading Outfit-Regular...
curl -s -o "assets\fonts\Outfit-Regular.woff2" "https://fonts.gstatic.com/s/outfit/v11/QGYvz_MVcBeFP4xwcxw.woff2"

echo TR: Outfit-Medium indiriliyor...
echo EN: Downloading Outfit-Medium...
curl -s -o "assets\fonts\Outfit-Medium.woff2" "https://fonts.gstatic.com/s/outfit/v11/QGYyz_MVcBeFP4xwcxw.woff2"

echo TR: Outfit-Bold indiriliyor...
echo EN: Downloading Outfit-Bold...
curl -s -o "assets\fonts\Outfit-Bold.woff2" "https://fonts.gstatic.com/s/outfit/v11/QGYsz_MVcBeFP4xwcxw.woff2"

echo TR: Outfit-Black indiriliyor...
echo EN: Downloading Outfit-Black...
curl -s -o "assets\fonts\Outfit-Black.woff2" "https://fonts.gstatic.com/s/outfit/v11/QGY2z_MVcBeFP4xwcxw.woff2"

REM TR: Poppins fontları
REM EN: Poppins fonts
echo TR: Poppins-Regular indiriliyor...
echo EN: Downloading Poppins-Regular...
curl -s -o "assets\fonts\Poppins-Regular.woff2" "https://fonts.gstatic.com/s/poppins/v20/pxiEyp8kv8JHgFVrJJfecg.woff2"

echo TR: Poppins-Medium indiriliyor...
echo EN: Downloading Poppins-Medium...
curl -s -o "assets\fonts\Poppins-Medium.woff2" "https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLz9Z1JlFc-K.woff2"

echo TR: Poppins-Bold indiriliyor...
echo EN: Downloading Poppins-Bold...
curl -s -o "assets\fonts\Poppins-Bold.woff2" "https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLz9Z1JlFc-K.woff2"

echo TR: Poppins-Black indiriliyor...
echo EN: Downloading Poppins-Black...
curl -s -o "assets\fonts\Poppins-Black.woff2" "https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLz9Z1JlFc-K.woff2"

REM TR: Inter fontları
REM EN: Inter fonts
echo TR: Inter-Regular indiriliyor...
echo EN: Downloading Inter-Regular...
curl -s -o "assets\fonts\Inter-Regular.woff2" "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hiA.woff2"

echo TR: Inter-Medium indiriliyor...
echo EN: Downloading Inter-Medium...
curl -s -o "assets\fonts\Inter-Medium.woff2" "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYAZ9hiA.woff2"

echo TR: Inter-SemiBold indiriliyor...
echo EN: Downloading Inter-SemiBold...
curl -s -o "assets\fonts\Inter-SemiBold.woff2" "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYAZ9hiA.woff2"

echo TR: Inter-Bold indiriliyor...
echo EN: Downloading Inter-Bold...
curl -s -o "assets\fonts\Inter-Bold.woff2" "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYAZ9hiA.woff2"

echo TR: Font indirme tamamlandı!
echo EN: Font download completed!
echo TR: Lütfen pubspec.yaml dosyasını kontrol edin
echo EN: Please check pubspec.yaml file
echo TR: ve "flutter pub get" komutunu çalıştırın
echo EN: and run "flutter pub get" command

pause
